# This file is part of ssh-python.
# Copyright (C) 2017-2021 Panos Kittenis and contributors.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation, version 2.1.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
version: 2.1
orbs:
  python: circleci/python@2.1.0
jobs:
  python_test:
    parameters:
      python_ver:
        type: string
        default: "3.9"
    docker:
      - image: cimg/python:<< parameters.python_ver >>
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements_dev.txt
          pkg-manager: pip
      - run:
          name: Deps
          command: |
            sudo apt-get update
            sudo apt-get install cmake openssh-server
      - run:
          command: |
            pip install -e .
            eval "$(ssh-agent -s)"
          name: Build
      - run:
          command: |
            set -x
            ls -lhtr ssh/
            pwd
            ldd -r ssh/session*.so
            pytest tests
            flake8 ssh
            python setup.py sdist
            cd dist; pip install *; cd ..
            cd doc
            make html
            cd ..
          name: Test

  linux-x86_64-wheels:
    working_directory: ~/linux-wheels
    docker:
      - image: cimg/python:3.9
    environment:
      CIBW_ARCHS_LINUX: "x86_64"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Linux wheels.
          command: |
            pip3 install --user cibuildwheel==2.12.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  linux-ppc64le-wheels:
    working_directory: ~/linux-wheels
    docker:
      - image: cimg/python:3.9
    environment:
      CIBW_ARCHS_LINUX: "ppc64le"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup QEMU emulator
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install ppc64le
      - run:
          name: Build the Linux wheels.
          command: |
            pip3 install --user cibuildwheel==2.12.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  linux-s390x-wheels:
    working_directory: ~/linux-wheels
    docker:
      - image: cimg/python:3.9
    environment:
      CIBW_ARCHS_LINUX: "s390x"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup QEMU emulator
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install s390x
      - run:
          name: Build the Linux wheels.
          command: |
            pip3 install --user cibuildwheel==2.12.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  linux-aarch64-wheels:
    working_directory: ~/linux-aarch64-wheels
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    environment:
      CIBW_ARCHS_LINUX: "aarch64"
    steps:
      - checkout
      - run:
          name: Build the Linux aarch64 wheels.
          command: |
            python3 -m pip install --user cibuildwheel==2.12.0
            python3 -m cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  osx-wheels:
    macos:
      xcode: 14.0.0
    working_directory: ~/osx-wheels
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      SYSTEM_LIBSSH: 1
    steps:
      - checkout
      - run:
          name: Build the OS X wheels.
          command: |
            pip3 install cibuildwheel==2.12.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

workflows:
  version: 2
  test:
    jobs:
      - python_test:
          matrix:
            parameters:
              python_ver:
                - "3.6"
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
          filters:
            tags:
              ignore: /.*/
  build-wheels:
    jobs:
      - linux-x86_64-wheels
      - linux-aarch64-wheels
      - linux-ppc64le-wheels
      - linux-s390x-wheels
      - osx-wheels